/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.tutorial.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.tutorial.model.MyStudent;
import com.liferay.tutorial.service.MyStudentLocalServiceUtil;

/**
 * The extended model base implementation for the MyStudent service. Represents a row in the &quot;MyStudent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MyStudentImpl}.
 * </p>
 *
 * @author annv
 * @see MyStudentImpl
 * @see com.liferay.tutorial.model.MyStudent
 * @generated
 */
public abstract class MyStudentBaseImpl extends MyStudentModelImpl
	implements MyStudent {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a my student model instance should use the {@link MyStudent} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			MyStudentLocalServiceUtil.addMyStudent(this);
		}
		else {
			MyStudentLocalServiceUtil.updateMyStudent(this);
		}
	}
}