/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.tutorial.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Validate_St service. Represents a row in the &quot;Validate_St&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.tutorial.model.impl.Validate_StModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.tutorial.model.impl.Validate_StImpl}.
 * </p>
 *
 * @author annv
 * @see Validate_St
 * @see com.liferay.tutorial.model.impl.Validate_StImpl
 * @see com.liferay.tutorial.model.impl.Validate_StModelImpl
 * @generated
 */
public interface Validate_StModel extends BaseModel<Validate_St> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a validate_ st model instance should use the {@link Validate_St} interface instead.
	 */

	/**
	 * Returns the primary key of this validate_ st.
	 *
	 * @return the primary key of this validate_ st
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this validate_ st.
	 *
	 * @param primaryKey the primary key of this validate_ st
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the student ID of this validate_ st.
	 *
	 * @return the student ID of this validate_ st
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this validate_ st.
	 *
	 * @param studentId the student ID of this validate_ st
	 */
	public void setStudentId(long studentId);

	/**
	 * Returns the code of this validate_ st.
	 *
	 * @return the code of this validate_ st
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this validate_ st.
	 *
	 * @param code the code of this validate_ st
	 */
	public void setCode(String code);

	/**
	 * Returns the fullname of this validate_ st.
	 *
	 * @return the fullname of this validate_ st
	 */
	@AutoEscape
	public String getFullname();

	/**
	 * Sets the fullname of this validate_ st.
	 *
	 * @param fullname the fullname of this validate_ st
	 */
	public void setFullname(String fullname);

	/**
	 * Returns the gender of this validate_ st.
	 *
	 * @return the gender of this validate_ st
	 */
	public boolean getGender();

	/**
	 * Returns <code>true</code> if this validate_ st is gender.
	 *
	 * @return <code>true</code> if this validate_ st is gender; <code>false</code> otherwise
	 */
	public boolean isGender();

	/**
	 * Sets whether this validate_ st is gender.
	 *
	 * @param gender the gender of this validate_ st
	 */
	public void setGender(boolean gender);

	/**
	 * Returns the birthday of this validate_ st.
	 *
	 * @return the birthday of this validate_ st
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this validate_ st.
	 *
	 * @param birthday the birthday of this validate_ st
	 */
	public void setBirthday(Date birthday);

	/**
	 * Returns the email of this validate_ st.
	 *
	 * @return the email of this validate_ st
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this validate_ st.
	 *
	 * @param email the email of this validate_ st
	 */
	public void setEmail(String email);

	/**
	 * Returns the address of this validate_ st.
	 *
	 * @return the address of this validate_ st
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this validate_ st.
	 *
	 * @param address the address of this validate_ st
	 */
	public void setAddress(String address);

	/**
	 * Returns the blog of this validate_ st.
	 *
	 * @return the blog of this validate_ st
	 */
	@AutoEscape
	public String getBlog();

	/**
	 * Sets the blog of this validate_ st.
	 *
	 * @param blog the blog of this validate_ st
	 */
	public void setBlog(String blog);

	/**
	 * Returns the mark of this validate_ st.
	 *
	 * @return the mark of this validate_ st
	 */
	public double getMark();

	/**
	 * Sets the mark of this validate_ st.
	 *
	 * @param mark the mark of this validate_ st
	 */
	public void setMark(double mark);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.tutorial.model.Validate_St validate_St);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.tutorial.model.Validate_St> toCacheModel();

	@Override
	public com.liferay.tutorial.model.Validate_St toEscapedModel();

	@Override
	public com.liferay.tutorial.model.Validate_St toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}