/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.tutorial.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.tutorial.model.Validate_Student;
import com.liferay.tutorial.service.Validate_StudentLocalServiceUtil;

/**
 * The extended model base implementation for the Validate_Student service. Represents a row in the &quot;Validate_Student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Validate_StudentImpl}.
 * </p>
 *
 * @author annv
 * @see Validate_StudentImpl
 * @see com.liferay.tutorial.model.Validate_Student
 * @generated
 */
public abstract class Validate_StudentBaseImpl extends Validate_StudentModelImpl
	implements Validate_Student {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a validate_ student model instance should use the {@link Validate_Student} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			Validate_StudentLocalServiceUtil.addValidate_Student(this);
		}
		else {
			Validate_StudentLocalServiceUtil.updateValidate_Student(this);
		}
	}
}