/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.tutorial.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.liferay.tutorial.model.Validate_Student;
import com.liferay.tutorial.model.Validate_StudentModel;
import com.liferay.tutorial.model.Validate_StudentSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Validate_Student service. Represents a row in the &quot;Validate_Student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.tutorial.model.Validate_StudentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Validate_StudentImpl}.
 * </p>
 *
 * @author annv
 * @see Validate_StudentImpl
 * @see com.liferay.tutorial.model.Validate_Student
 * @see com.liferay.tutorial.model.Validate_StudentModel
 * @generated
 */
@JSON(strict = true)
public class Validate_StudentModelImpl extends BaseModelImpl<Validate_Student>
	implements Validate_StudentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a validate_ student model instance should use the {@link com.liferay.tutorial.model.Validate_Student} interface instead.
	 */
	public static final String TABLE_NAME = "Validate_Student";
	public static final Object[][] TABLE_COLUMNS = {
			{ "studentId", Types.BIGINT },
			{ "code_", Types.VARCHAR },
			{ "fullname", Types.VARCHAR },
			{ "gender", Types.BOOLEAN },
			{ "birthday", Types.TIMESTAMP },
			{ "email", Types.VARCHAR },
			{ "address", Types.VARCHAR },
			{ "blog", Types.VARCHAR },
			{ "mark", Types.DOUBLE }
		};
	public static final String TABLE_SQL_CREATE = "create table Validate_Student (studentId LONG not null primary key,code_ VARCHAR(75) null,fullname VARCHAR(75) null,gender BOOLEAN,birthday DATE null,email VARCHAR(75) null,address VARCHAR(75) null,blog VARCHAR(75) null,mark DOUBLE)";
	public static final String TABLE_SQL_DROP = "drop table Validate_Student";
	public static final String ORDER_BY_JPQL = " ORDER BY validate_Student.studentId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Validate_Student.studentId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.tutorial.model.Validate_Student"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.tutorial.model.Validate_Student"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.tutorial.model.Validate_Student"),
			true);
	public static long GENDER_COLUMN_BITMASK = 1L;
	public static long STUDENTID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Validate_Student toModel(Validate_StudentSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Validate_Student model = new Validate_StudentImpl();

		model.setStudentId(soapModel.getStudentId());
		model.setCode(soapModel.getCode());
		model.setFullname(soapModel.getFullname());
		model.setGender(soapModel.getGender());
		model.setBirthday(soapModel.getBirthday());
		model.setEmail(soapModel.getEmail());
		model.setAddress(soapModel.getAddress());
		model.setBlog(soapModel.getBlog());
		model.setMark(soapModel.getMark());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Validate_Student> toModels(
		Validate_StudentSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Validate_Student> models = new ArrayList<Validate_Student>(soapModels.length);

		for (Validate_StudentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.tutorial.model.Validate_Student"));

	public Validate_StudentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _studentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStudentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _studentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Validate_Student.class;
	}

	@Override
	public String getModelClassName() {
		return Validate_Student.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("studentId", getStudentId());
		attributes.put("code", getCode());
		attributes.put("fullname", getFullname());
		attributes.put("gender", getGender());
		attributes.put("birthday", getBirthday());
		attributes.put("email", getEmail());
		attributes.put("address", getAddress());
		attributes.put("blog", getBlog());
		attributes.put("mark", getMark());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long studentId = (Long)attributes.get("studentId");

		if (studentId != null) {
			setStudentId(studentId);
		}

		String code = (String)attributes.get("code");

		if (code != null) {
			setCode(code);
		}

		String fullname = (String)attributes.get("fullname");

		if (fullname != null) {
			setFullname(fullname);
		}

		Boolean gender = (Boolean)attributes.get("gender");

		if (gender != null) {
			setGender(gender);
		}

		Date birthday = (Date)attributes.get("birthday");

		if (birthday != null) {
			setBirthday(birthday);
		}

		String email = (String)attributes.get("email");

		if (email != null) {
			setEmail(email);
		}

		String address = (String)attributes.get("address");

		if (address != null) {
			setAddress(address);
		}

		String blog = (String)attributes.get("blog");

		if (blog != null) {
			setBlog(blog);
		}

		Double mark = (Double)attributes.get("mark");

		if (mark != null) {
			setMark(mark);
		}
	}

	@JSON
	@Override
	public long getStudentId() {
		return _studentId;
	}

	@Override
	public void setStudentId(long studentId) {
		_columnBitmask = -1L;

		_studentId = studentId;
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return StringPool.BLANK;
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_code = code;
	}

	@JSON
	@Override
	public String getFullname() {
		if (_fullname == null) {
			return StringPool.BLANK;
		}
		else {
			return _fullname;
		}
	}

	@Override
	public void setFullname(String fullname) {
		_fullname = fullname;
	}

	@JSON
	@Override
	public boolean getGender() {
		return _gender;
	}

	@Override
	public boolean isGender() {
		return _gender;
	}

	@Override
	public void setGender(boolean gender) {
		_columnBitmask |= GENDER_COLUMN_BITMASK;

		if (!_setOriginalGender) {
			_setOriginalGender = true;

			_originalGender = _gender;
		}

		_gender = gender;
	}

	public boolean getOriginalGender() {
		return _originalGender;
	}

	@JSON
	@Override
	public Date getBirthday() {
		return _birthday;
	}

	@Override
	public void setBirthday(Date birthday) {
		_birthday = birthday;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		_address = address;
	}

	@JSON
	@Override
	public String getBlog() {
		if (_blog == null) {
			return StringPool.BLANK;
		}
		else {
			return _blog;
		}
	}

	@Override
	public void setBlog(String blog) {
		_blog = blog;
	}

	@JSON
	@Override
	public double getMark() {
		return _mark;
	}

	@Override
	public void setMark(double mark) {
		_mark = mark;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Validate_Student.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Validate_Student toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Validate_Student)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Validate_StudentImpl validate_StudentImpl = new Validate_StudentImpl();

		validate_StudentImpl.setStudentId(getStudentId());
		validate_StudentImpl.setCode(getCode());
		validate_StudentImpl.setFullname(getFullname());
		validate_StudentImpl.setGender(getGender());
		validate_StudentImpl.setBirthday(getBirthday());
		validate_StudentImpl.setEmail(getEmail());
		validate_StudentImpl.setAddress(getAddress());
		validate_StudentImpl.setBlog(getBlog());
		validate_StudentImpl.setMark(getMark());

		validate_StudentImpl.resetOriginalValues();

		return validate_StudentImpl;
	}

	@Override
	public int compareTo(Validate_Student validate_Student) {
		int value = 0;

		if (getStudentId() < validate_Student.getStudentId()) {
			value = -1;
		}
		else if (getStudentId() > validate_Student.getStudentId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Validate_Student)) {
			return false;
		}

		Validate_Student validate_Student = (Validate_Student)obj;

		long primaryKey = validate_Student.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		Validate_StudentModelImpl validate_StudentModelImpl = this;

		validate_StudentModelImpl._originalGender = validate_StudentModelImpl._gender;

		validate_StudentModelImpl._setOriginalGender = false;

		validate_StudentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Validate_Student> toCacheModel() {
		Validate_StudentCacheModel validate_StudentCacheModel = new Validate_StudentCacheModel();

		validate_StudentCacheModel.studentId = getStudentId();

		validate_StudentCacheModel.code = getCode();

		String code = validate_StudentCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			validate_StudentCacheModel.code = null;
		}

		validate_StudentCacheModel.fullname = getFullname();

		String fullname = validate_StudentCacheModel.fullname;

		if ((fullname != null) && (fullname.length() == 0)) {
			validate_StudentCacheModel.fullname = null;
		}

		validate_StudentCacheModel.gender = getGender();

		Date birthday = getBirthday();

		if (birthday != null) {
			validate_StudentCacheModel.birthday = birthday.getTime();
		}
		else {
			validate_StudentCacheModel.birthday = Long.MIN_VALUE;
		}

		validate_StudentCacheModel.email = getEmail();

		String email = validate_StudentCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			validate_StudentCacheModel.email = null;
		}

		validate_StudentCacheModel.address = getAddress();

		String address = validate_StudentCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			validate_StudentCacheModel.address = null;
		}

		validate_StudentCacheModel.blog = getBlog();

		String blog = validate_StudentCacheModel.blog;

		if ((blog != null) && (blog.length() == 0)) {
			validate_StudentCacheModel.blog = null;
		}

		validate_StudentCacheModel.mark = getMark();

		return validate_StudentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{studentId=");
		sb.append(getStudentId());
		sb.append(", code=");
		sb.append(getCode());
		sb.append(", fullname=");
		sb.append(getFullname());
		sb.append(", gender=");
		sb.append(getGender());
		sb.append(", birthday=");
		sb.append(getBirthday());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", address=");
		sb.append(getAddress());
		sb.append(", blog=");
		sb.append(getBlog());
		sb.append(", mark=");
		sb.append(getMark());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.liferay.tutorial.model.Validate_Student");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>studentId</column-name><column-value><![CDATA[");
		sb.append(getStudentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>code</column-name><column-value><![CDATA[");
		sb.append(getCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fullname</column-name><column-value><![CDATA[");
		sb.append(getFullname());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gender</column-name><column-value><![CDATA[");
		sb.append(getGender());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>birthday</column-name><column-value><![CDATA[");
		sb.append(getBirthday());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>address</column-name><column-value><![CDATA[");
		sb.append(getAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>blog</column-name><column-value><![CDATA[");
		sb.append(getBlog());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mark</column-name><column-value><![CDATA[");
		sb.append(getMark());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Validate_Student.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Validate_Student.class
		};
	private long _studentId;
	private String _code;
	private String _fullname;
	private boolean _gender;
	private boolean _originalGender;
	private boolean _setOriginalGender;
	private Date _birthday;
	private String _email;
	private String _address;
	private String _blog;
	private double _mark;
	private long _columnBitmask;
	private Validate_Student _escapedModel;
}